baseURL = "https://vishvAsa.github.io/purANam/"
languageCode = "en-us"
title = "पुराणे विश्वासटिप्पन्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vishvAsa/purANam/edit/content/"
  contactLink = "https://github.com/vishvAsa/purANam/issues/new"
  fullSearchURL = "/full_search"
  env = "production"  
  disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true